name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make MyCalculator
    - name: make-par
      run: make MyCalculator-par
    - name: upload artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        path: |
          MyCalculator
          MyCalculator-par
          third-party-licenses/*
          config.ini
